import Foundation

/// Tokens split the way providers charge for them.
///
/// Session files record these counts; UsageNow never sends them anywhere and
/// uses them only to total activity and to estimate what that activity would
/// cost at list prices.
struct TokenBreakdown: Sendable, Equatable {
    var input: Int64 = 0
    var output: Int64 = 0
    /// Tokens written into a prompt cache, charged above the input rate.
    var cacheWrite: Int64 = 0
    /// Tokens read back from a prompt cache, charged well below it.
    var cacheRead: Int64 = 0

    var isEmpty: Bool { input == 0 && output == 0 && cacheWrite == 0 && cacheRead == 0 }

    var total: Int64 { input + output + cacheWrite + cacheRead }

    static func + (lhs: TokenBreakdown, rhs: TokenBreakdown) -> TokenBreakdown {
        TokenBreakdown(
            input: lhs.input + rhs.input,
            output: lhs.output + rhs.output,
            cacheWrite: lhs.cacheWrite + rhs.cacheWrite,
            cacheRead: lhs.cacheRead + rhs.cacheRead
        )
    }
}

/// What one model charges per million tokens, in USD, at list prices.
///
/// `cacheWrite` and `cacheRead` are absent for models whose provider doesn't
/// price cached tokens separately.
struct ModelPrice: Sendable, Equatable {
    var input: Decimal
    var output: Decimal
    var cacheWrite: Decimal?
    var cacheRead: Decimal?
}

/// List prices for the models UsageNow may see in local sessions.
///
/// The table is generated by `scripts/update-model-prices.py` and shipped in
/// the bundle, so estimating a cost needs no network access, no account, and
/// no credentials. A model missing from the table has no estimate — a price
/// is never guessed from a similar name, because a wrong number looks exactly
/// as convincing as a right one.
struct ModelPriceTable: Sendable {
    /// The day the table was generated, for the "prices as of" note.
    let generated: Date?
    private let prices: [String: ModelPrice]

    /// The table shipped in this bundle, or an empty one if it's missing.
    static let bundled: ModelPriceTable = {
        guard let url = Bundle.main.url(forResource: "ModelPrices", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let table = try? ModelPriceTable(data: data)
        else { return ModelPriceTable(generated: nil, prices: [:]) }
        return table
    }()

    init(generated: Date?, prices: [String: ModelPrice]) {
        self.generated = generated
        self.prices = prices
    }

    init(data: Data) throws {
        let file = try JSONDecoder().decode(PriceFile.self, from: data)
        generated = file.generated.flatMap { try? Date($0, strategy: .iso8601.year().month().day()) }
        prices = file.models.reduce(into: [:]) { result, entry in
            guard let input = Decimal(string: entry.value.input),
                  let output = Decimal(string: entry.value.output)
            else { return }
            result[entry.key.lowercased()] = ModelPrice(
                input: input,
                output: output,
                cacheWrite: entry.value.cacheWrite.flatMap { Decimal(string: $0) },
                cacheRead: entry.value.cacheRead.flatMap { Decimal(string: $0) }
            )
        }
    }

    var isEmpty: Bool { prices.isEmpty }

    /// The price for a model identifier as a tool records it.
    ///
    /// Matching is deliberately narrow: the identifier as written, without a
    /// vendor prefix, without a trailing date stamp, and without `-latest`.
    /// Anything else returns `nil`.
    func price(for modelID: String) -> ModelPrice? {
        for candidate in Self.candidates(for: modelID) {
            if let price = prices[candidate] { return price }
        }
        return nil
    }

    /// What this activity would have cost at list prices, in USD.
    ///
    /// Tokens in a bucket the model has no separate price for — a cache write
    /// on a provider that doesn't charge for one — are priced as input.
    func cost(of tokens: TokenBreakdown, model: String) -> Decimal? {
        guard let price = price(for: model) else { return nil }
        let million: Decimal = 1_000_000
        let amounts: [(Int64, Decimal)] = [
            (max(0, tokens.input), price.input),
            (max(0, tokens.output), price.output),
            (max(0, tokens.cacheWrite), price.cacheWrite ?? price.input),
            (max(0, tokens.cacheRead), price.cacheRead ?? price.input),
        ]
        let total = amounts.reduce(Decimal.zero) { $0 + Decimal($1.0) * $1.1 }
        return total / million
    }

    private static func candidates(for modelID: String) -> [String] {
        let trimmed = modelID.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !trimmed.isEmpty else { return [] }

        var names = [trimmed]
        if let slash = trimmed.lastIndex(of: "/") {
            names.append(String(trimmed[trimmed.index(after: slash)...]))
        }

        return names.flatMap { name -> [String] in
            var forms = [name]
            if name.hasSuffix("-latest") { forms.append(String(name.dropLast("-latest".count))) }
            for form in forms where form.count > 9 {
                // A date stamp the vendor appends to a released model:
                // "claude-sonnet-5-20260514" is priced as "claude-sonnet-5".
                let stamp = form.suffix(9)
                if stamp.first == "-", stamp.dropFirst().allSatisfy(\.isNumber) {
                    forms.append(String(form.dropLast(9)))
                }
            }
            return forms
        }
    }

    private struct PriceFile: Decodable {
        struct Entry: Decodable {
            var input: String
            var output: String
            var cacheWrite: String?
            var cacheRead: String?
        }

        var generated: String?
        var models: [String: Entry]
    }
}
